# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "pypy3"

env:
  - KOMBU_VERSION=3.0.36
  - KOMBU_VERSION=4.0.2

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install kombu==$KOMBU_VERSION
  - pip install -r requirements/test.txt

# command to run tests, e.g. python setup.py test
script: python setup.py nosetests
