name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        docker-image:
          - 'python:2.7'
          - 'python:3.6'
          - 'pypy:2.7'
        kombu-version: ['3.0.36', '4.0.2']

    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run --rm \
            -v $PWD:/app \
            -w /app \
            -e KOMBU_VERSION=${{ matrix.kombu-version }} \
            {{ matrix.docker-image }} \
            make install-and-test
